apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spanner-app
  labels:
    app: hello-spanner-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spanner-app
  template:
    metadata:
      labels:
        app: hello-spanner-app
    spec:
      containers:
      - name: hello-spanner-app
        image: gcr.io/<PROJECT_ID>/hello-spanner-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
