apiVersion: v1
kind: Service
metadata:
  name: hello-spanner-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-spanner-app
  serviceAccountName: <KSA_NAME>
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
